export const SCRAPPING_CLASSES_OTAKUDESU = {
  CONTAINER: "ul li .detpost",
  NAME: ".thumbz .jdlflm",
  EPISODE: ".epz",
  SEARCHED_ANIME: ".chivsrc h2 a",
  GENRES: ".genres li a",
  ANIME_BY_GENRE: ".venser .page div",
  DETAIL: ".infozingle p span",
  SYNOPSIS: ".sinopc",
  DOWNLOAD_LINK_EPISODE: ".episodelist:nth(1) ul li span a",
  DOWNLOAD_LINK_BATCH: ".episodelist:nth(0) ul li span a",
  IFRAME_CONTAINER: ".responsive-embed-stream iframe",
  DOWNLOADS: {
    EPISODE: ".download ul li",
    BATCH: ".batchlink ul li",
    RESO: "strong",
    ANCHOR: "a",
    SIZE: "i",
  },
};
